### ISSUE TITLE
Document release flow

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-genesis-tinkerer#11]
Establish what Cosmos SDK (or how much we want to lag behind the latest release).
Make a release flow that other repos can use as a guideline.

**Comment by dasanchez** [comment]
- Talk to @benhylau about any release processes used in other engineering projects
- See what other Cosmos projects are doing

**Comment by uditvira** [comment]
Working here https://hackmd.io/Rg-8NWwQQQyMDXlTYT5q-w?view

**Comment by uditvira** [comment]
Added to the wiki https://github.com/hyphacoop/cosmos-configurations-private/wiki/Release-process
