### ISSUE TITLE
Generate a tinkered mainnet genesis bimonthly

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-genesis-tinkerer#20]
Do the following once every two weeks:
1. Generate an exported genesis file on a mainnet node
2. Tinker the genesis file to give majority voting power to a single account
3. Publish the tinkered file to the `tests` folder

**Comment by dasanchez** [comment]
I'm wondering how many genesis files we should aim to offer.

GitHub has this [doc with a section on repo size limits](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits) where they say staying under 5GB is strongly recommended and ideally repos should be less than 1GB. I don't know if we want to test the 5GB recommendation 😅 

If each mainnet export comes in at 180MB, should we keep the list of genesis files trimmed to just the last five?

**Comment by ASoTNetworks** [comment]
Currently we are using https://git-lfs.github.com/ to store the genesis files as there's a 100MB file size limit. When cloning the repo it only downloads the identifier for the file.

We currently have 1G LFS storage on github.

**Comment by dasanchez** [comment]
Done, see cosmos-ansible repo:
https://github.com/hyphacoop/cosmos-ansible/pull/93
