### ISSUE TITLE
Improve how we do preprocessing

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-genesis-tinkerer#6]
Some operations are better done as string replacements rather than manipulations to the json structure.

```
PREPROCESSED_FILE = GENESIS_ARCHIVE + ".preprocessed.json"

shutil.copy2(GENESIS_ARCHIVE, PREPROCESSED_FILE)

subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_SELF_DELEGATION_ADDR    + "%" + EARTH_SELF_DELEGATION_ADDR   + "%g",PREPROCESSED_FILE])
subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_SELF_DELEGATION_PUBKEY  + "%" + EARTH_SELF_DELEGATION_PUBKEY + "%g",PREPROCESSED_FILE])
subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_VALIDATOR_OP_ADDRESS    + "%" + EARTH_VALIDATOR_OP_ADDRESS   + "%g",PREPROCESSED_FILE])

subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_PUBKEY       + "%" + EARTH_PUBKEY       + "%g",PREPROCESSED_FILE])
subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_ADDRESS      + "%" + EARTH_ADDRESS      + "%g",PREPROCESSED_FILE])
subprocess.call(["sed", "-i", ".bak", "s%" + COINBASE_CONS_ADDRESS + "%" + EARTH_CONS_ADDRESS + "%g",PREPROCESSED_FILE])
```
@RangerMauve suggests two steps:

1. load the file as bytes and do a byte replacement
2. load json and then do structural replacements

**Comment by RangerMauve** [comment]
More details

- Add a new private variable to the `GenesisTinkerer` class, `action_queue` which is a list (empty by default)
- Add a new private variable to the `GenesisTinkerer` class, `replace_queue` which is a list (empty by default)
- Replace all the existing methods that perform changes to the genesis file with two others
  - Mark the existing method as private
  - Add a new public method with the same name, which will push a dict to the `action_queue`
- Add a new action called "replace" which takes two arguments (original_value, new_value)
  - Check that they are the same length and throw an error if they aren't.
  - Add an action to the `replace_queue`
  - Check if the `action_queue` has items in it. If it does throw an error saying that replace must be called before any other actions
- Modify logic for loading genesis files to run replacements on the byte stream as it goes
  - This might be hard to do?
  - Gotta load the file as a binary stream
  - Use a generator to process the chunks of data
  - Iterate through the replacements
  - Check if the `old_value` is within the chunk, if it is, replace it
  - Check if there's a subrange within the current chunk that starts with the start of the `old_value`, and ends at the end of the chunk
  - If there isn't yield it, else get the next chunk and append to the current chunk and try iterating again
  - Figure out how to pass this generator into the `json.load` method to take advantage of the streaming read
- Add a new method (call it `run` or `run_actions` or `run_steps` or something along those lines)
  - If the genesis file hasn't been loaded, load it, this should also trigger the replacements as the file is being parsed
  - Iterate through the `action_queue` and perform each action (the types should have a `name` and set of arguments, which you can then call on the `self` variable. Might need a gross `if` statement?
  - At the end, try to auto-save

**Comment by dasanchez** [comment]
See #12
